# Generated by Django 3.0.3 on 2020-02-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cas', models.CharField(max_length=25, null=True)),
                ('synonyms', models.TextField(null=True)),
                ('formula', models.CharField(max_length=250, null=True)),
                ('molecular_weight', models.FloatField(default=0.0)),
                ('density', models.FloatField(default=0.0)),
                ('smiles', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=1)),
                ('contact_information', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Premesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('building', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.Department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.UserRole')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='premesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.Premesis'),
        ),
        migrations.AddField(
            model_name='department',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.DepartmentRole'),
        ),
        migrations.CreateModel(
            name='ChemicalBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.Shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('size_unit', models.CharField(choices=[('g', 'grams'), ('ml', 'milliliters')], max_length=10)),
                ('amount_remaining', models.FloatField()),
                ('cost', models.IntegerField(default=0)),
                ('usable', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.ChemicalBox')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.Chemical')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chemicals.Supplier')),
            ],
        ),
    ]
